spring.application.name=intellispace-backend

spring.threads.virtual.enabled=true

# ===============================
# Database
# ===============================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# Flyway
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=60

# ===============================
# Server
# ===============================
server.port=${PORT:8080}

# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,info